import turtle
screen=turtle.Screen()
t=turtle.Turtle()
screen.title("India's flag ")
t.shape()
t.speed(-1)
t.penup()
t.goto(-700,350)
t.pendown()
t.color("orangered")
t.begin_fill()
t.forward(1400)
t.right(90)
t.forward(233)
t.right(90)
t.forward(1400)
t.end_fill()
t.left(90)
t.forward(233)
t.color("green")
t.begin_fill()
t.forward(233)
t.left(90)
t.forward(1400)
t.left(90)
t.forward(233)
t.end_fill()
t.penup()
t.goto(80,0)
t.penup()
t.color("navy")
t.begin_fill()
t.circle(80)
t.end_fill()
t.penup()
t.goto(70, 0)
t.pendown()
t.color("white")
t.begin_fill()
t.circle(70)
t.end_fill()
t.penup()
t.goto(-66,9)
t.pendown()
t.color("navy")
for i in range(24):
    t.speed(-100)
    t.begin_fill()
    t.circle(4.5)
    t.end_fill()
    t.penup()
    t.right(15)
    t.forward(17.5)
    t.pendown()
t.penup()
t.goto(0,0)
t.pendown()
t.pensize(3)

for i in range(24):
    t.forward(60)
    t.backward(60)
    t.left(15)

#code by Gowrishankar 
#turtle oru rasamflag

turtle.done()